- name: Pre tasks
  hosts: localhost
  connection: local
  user: ubuntu
  pre_tasks:
    - name: Install Ansible roles
      ansible.builtin.command:
        cmd: ansible-galaxy install --force -r requirements.yaml
