- name: Pre tasks
  hosts: localhost
  connection: local
  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_edition: ce
        docker_packages:
          - docker-ce={{ docker_version }}
          - docker-ce-cli={{ docker_version }}
          - docker-ce-rootless-extras={{ docker_version }}
          - containerd.io
        docker_users:
          - ubuntu
  