- name: Ansible Example Pull Mode
  hosts: localhost
  user: root
  connection: local
  tasks:
    - name: Test pull mode
      shell: touch /tmp/ansible-pull_mode

- name: log hostname
  debug:
    msg: "Hostname is {{ ansible_hostname }}"
