- name: Pre tasks
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Greeting in a pre_task
      ansible.builtin.debug:
        msg: "Hey this is a demo of Ansible pull running on host: {{ ansible_hostname }}"
    - name: Install Ansible roles
      ansible.builtin.command:
        cmd: ansible-galaxy install --force -r requirements.yaml
      become: yes

- name: Install Docker
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.docker
      vars:
        docker_edition: ce
        docker_packages:
          - docker-ce={{ docker_version }}
          - docker-ce-cli={{ docker_version }}
          - docker-ce-rootless-extras={{ docker_version }}
          - containerd.io
        docker_users:
          - ubuntu
  